### ISSUE TITLE
(ThreadError) "Attempt to unlock a mutex which is not locked"

### ISSUE THREAD

**Issue by rajofchennai** [iconara/cql-rb#68]
I am getting this error randomly from my application. I am using ruby2.0.0. This happens when I use cql-rb in a threaded environment (sidekiq). 

```
A ThreadError occurred in background at 2014-01-10 07:26:44 UTC :

  Attempt to unlock a mutex which is not locked
  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:188:in `synchronize'

  -------------------------------
Backtrace:
-------------------------------

  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:187:in `pop'
  /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/cql-rb-1.1.3/lib/cql/future.rb:344:in `value'
  /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/cql-rb-1.1.3/lib/cql/client/synchronous_client.rb:54:in `block in execute'
  /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/cql-rb-1.1.3/lib/cql/client/synchronous_client.rb:8:in `synchronous_backtrace'
  /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/cql-rb-1.1.3/lib/cql/client/synchronous_client.rb:54:in `execute'
```

**Comment by sodabrew** [comment]
Same problem has been reported upstream. If you have any more information that can help upstream Ruby devs get a handle on the problem, please post to:
https://bugs.ruby-lang.org/issues/9132
https://bugs.ruby-lang.org/issues/9432
